# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-03 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirppu', '0013_add_receipt_suspend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='sell_time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='receipt',
            name='type',
            field=models.CharField(choices=[('PURCHASE', 'Purchase'), ('COMPENSATION', 'Compensation')], default='PURCHASE', max_length=16),
        ),
    ]
