# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirppu', '0015_receiptextrarow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uitext',
            name='identifier',
            field=models.CharField(help_text='Identifier of the textitem', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='uitext',
            name='text',
            field=models.CharField(blank=True, help_text='Textitem in UI', max_length=16384),
        ),
    ]
