# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 13:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import kirppu.models


class Migration(migrations.Migration):

    dependencies = [
        ('kirppu', '0017_add_representative_releation_to_box'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryAccessPermit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('expiration_time', models.DateTimeField(default=kirppu.models.default_temporary_access_permit_expiry)),
                ('state', models.CharField(choices=[('new', 'Unused'), ('use', 'In use'), ('exh', 'Exhausted'), ('inv', 'Invalidated')], max_length=8)),
                ('short_code', models.CharField(max_length=128, unique=True, validators=[django.core.validators.MinLengthValidator(4)])),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kirppu.Clerk')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kirppu.Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryAccessPermitLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('add', 'Add'), ('try', 'Try using'), ('use', 'Use'), ('del', 'Delete'), ('inv', 'Invalidate')], max_length=16)),
                ('address', models.CharField(max_length=512)),
                ('peer', models.CharField(max_length=1024)),
                ('permit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='kirppu.TemporaryAccessPermit')),
            ],
        ),
    ]
