# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-03 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirppu', '0018_add_temporary_permits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='adult',
            field=models.CharField(choices=[('yes', 'Item allowed only to adult shoppers, contains porn etc.'), ('no', 'Item allowed to all shoppers')], default='no', max_length=8),
        ),
        migrations.AlterField(
            model_name='item',
            name='state',
            field=models.CharField(choices=[('AD', 'Advertised'), ('BR', 'Brought to event'), ('ST', 'Staged for selling'), ('SO', 'Sold'), ('MI', 'Missing'), ('RE', 'Returned to vendor'), ('CO', 'Compensated to vendor')], default='AD', max_length=8),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('tiny', 'Tiny price tag'), ('short', 'Short price tag'), ('long', 'Long price tag')], default='short', max_length=8),
        ),
        migrations.AlterField(
            model_name='itemstatelog',
            name='new_state',
            field=models.CharField(choices=[('AD', 'Advertised'), ('BR', 'Brought to event'), ('ST', 'Staged for selling'), ('SO', 'Sold'), ('MI', 'Missing'), ('RE', 'Returned to vendor'), ('CO', 'Compensated to vendor')], max_length=2),
        ),
        migrations.AlterField(
            model_name='itemstatelog',
            name='old_state',
            field=models.CharField(choices=[('AD', 'Advertised'), ('BR', 'Brought to event'), ('ST', 'Staged for selling'), ('SO', 'Sold'), ('MI', 'Missing'), ('RE', 'Returned to vendor'), ('CO', 'Compensated to vendor')], max_length=2),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='action',
            field=models.CharField(choices=[('ADD', 'Added to receipt'), ('RL', 'Removed later'), ('DEL', 'Removed from receipt')], default='ADD', max_length=16),
        ),
        migrations.AlterField(
            model_name='temporaryaccesspermit',
            name='state',
            field=models.CharField(choices=[('new', 'Unused'), ('use', 'In use'), ('exh', 'Exhausted'), ('inv', 'Invalidated')], default='new', max_length=8),
        ),
    ]
