# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-08 12:17
from __future__ import unicode_literals

from django.db import migrations, models
from django.db.models import F


# noinspection PyPep8Naming
def migrate_order(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    ItemType = apps.get_model("kirppu", "ItemType")
    ItemType.objects.using(db_alias).all().update(order=F("id") * 10)


class Migration(migrations.Migration):

    dependencies = [
        ('kirppu', '0020_add_item_type_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='order',
            field=models.IntegerField(null=True),
            preserve_default=False,
        ),
        migrations.RunPython(
            code=migrate_order,
            # No need to reverse value setting when it exists solely for filling unique constraint.
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='order',
            field=models.IntegerField(unique=True),
        ),
    ]
