# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-22 06:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kirppu', '0021_itemtype_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('phone', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='vendor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendor',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kirppu.Person'),
        ),
        migrations.AlterUniqueTogether(
            name='vendor',
            unique_together=set([('user', 'person')]),
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'permissions': (
            ('can_switch_sub_vendor', 'Can switch to created sub-Vendors'), ('can_create_sub_vendor', 'Can create new sub-Vendors'))},
        ),
    ]
