# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-05 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirppu', '0022_separate_vendor_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='bundle_size',
            field=models.IntegerField(default=1, help_text='How many items are sold in a bundle'),
        ),
    ]
