# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-08 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirppu', '0023_box_bundle_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='mobile_view_visited',
            field=models.BooleanField(default=False),
        ),
    ]
