# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-07 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kirppu', '0024_vendor_mobile_view_visited'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemstatelog',
            options={'permissions': (('view_statistics', 'Can see statistics'),)},
        ),
    ]
