# Generated by Django 2.0.10 on 2019-02-09 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kirppu', '0025_add_statistics_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'permissions': (('view_accounting', 'View accounting data'),)},
        ),
    ]
