# Generated by Django 2.2.1 on 2019-05-30 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kirppu', '0027_allow_blank_clerk_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=250)),
                ('home_page', models.URLField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('registration_end', models.DateTimeField(blank=True, null=True)),
                ('checkout_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='clerk',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kirppu.Event'),
        ),
        migrations.AddField(
            model_name='counter',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kirppu.Event'),
        ),
        migrations.AddField(
            model_name='itemtype',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kirppu.Event'),
        ),
        migrations.AddField(
            model_name='uitext',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kirppu.Event'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kirppu.Event'),
        ),
        migrations.AlterUniqueTogether(
            name='vendor',
            unique_together={('user', 'person', 'event')},
        ),

        # Box constraints
        migrations.AlterField(
            model_name='box',
            name='box_number',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),

        # Clerk constraints
        migrations.RemoveConstraint(
            model_name='clerk',
            name='unique_user',
        ),
        migrations.AddConstraint(
            model_name='clerk',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='unique_event_clerk'),
        ),

        # Counter constraints
        migrations.AlterField(
            model_name='counter',
            name='identifier',
            field=models.CharField(blank=True, help_text='Registration identifier of the counter', max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='counter',
            unique_together={('event', 'identifier')},
        ),

        # UIText constraints
        migrations.AlterField(
            model_name='uitext',
            name='identifier',
            field=models.CharField(help_text='Identifier of the textitem', max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name='uitext',
            unique_together={('event', 'identifier')},
        ),

        # ItemType constraints
        migrations.AlterField(
            model_name='itemtype',
            name='key',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='itemtype',
            unique_together={('event', 'key'), ('event', 'order')},
        ),
    ]
