# Generated by Django 4.2.11 on 2024-04-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirppu', '0046_add_vendor_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_disabled',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_disabled',
            field=models.BooleanField(default=True, help_text='When set, registration is disabled even if registration end is set. If not set, registration is enabled until registration end if that is set.'),
        ),
    ]
